### ISSUE TITLE
hadoop incompatibilities

### ISSUE THREAD

**Issue by yinshurman** [alexarchambault/sbt-ammonite#15]
everything worked well in the default sbt scala REPL ,but reported the following Error when i switched to the sbt-ammonite:
`import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.hbase._
import org.apache.hadoop.hbase.client._
import org.apache.hadoop.hbase.util.Bytes
import scala.collection.JavaConversions._
import collection.JavaConverters._
import scala.collection.mutable.ListBuffer
import org.apache.hadoop.hbase.filter._
import org.apache.hadoop.hbase.mapreduce.TableInputFormat
import org.apache.hadoop.hbase.mapreduce.TableMapReduceUtil
import org.apache.hadoop.hbase.io.ImmutableBytesWritable
import org.apache.hadoop.hbase.protobuf.ProtobufUtil
import org.apache.hadoop.hbase.protobuf.generated.ClientProtos

import org.apache.spark._
import org.apache.spark.sql._
`
` val config=new Configuration() `

and the following Error occured:

`scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving object InterfaceAudience
  scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1477)
  scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1475)
  scala.Function0$class.apply$mcV$sp(Function0.scala:34)
  scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:533)
  scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1475)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
  scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.info(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$coreLookup$1(JavaMirrors.scala:991)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$lookupClass$1(JavaMirrors.scala:997)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:1002)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
  scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
  scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
  scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
  scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
  scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
  scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy.<init>(JavaMirrors.scala:163)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:162)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:162)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$copyAnnotations(JavaMirrors.scala:683)
  scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.load(JavaMirrors.scala:733)
  scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.complete(JavaMirrors.scala:744)
  scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1489)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
  scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$2.info(SynchronizedSymbols.scala:171)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$coreLookup$1(JavaMirrors.scala:991)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$lookupClass$1(JavaMirrors.scala:997)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:1002)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
  scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
  scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
  scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
  scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
  scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
  scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:979)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy.<init>(JavaMirrors.scala:163)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:162)
  scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:162)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
  scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$copyAnnotations(JavaMirrors.scala:683)
  scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.load(JavaMirrors.scala:733)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeParams$1.apply(SynchronizedSymbols.scala:142)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeParams$1.apply(SynchronizedSymbols.scala:133)
  scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
  scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.typeParams(SynchronizedSymbols.scala:132)
  scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.typeParams(SynchronizedSymbols.scala:168)
  scala.reflect.internal.Types$class.isRawIfWithoutArgs(Types.scala:3753)
  scala.reflect.internal.SymbolTable.isRawIfWithoutArgs(SymbolTable.scala:16)
  scala.reflect.internal.Types$class.isRawType(Types.scala:3758)
  scala.reflect.internal.SymbolTable.isRawType(SymbolTable.scala:16)
  scala.reflect.internal.Types$class.normalizePlus(Types.scala:3930)
  scala.reflect.internal.SymbolTable.normalizePlus(SymbolTable.scala:16)
  scala.reflect.internal.tpe.TypeComparers$class.isSameType2(TypeComparers.scala:236)
  scala.reflect.internal.SymbolTable.isSameType2(SymbolTable.scala:16)
  scala.reflect.internal.tpe.TypeComparers$class.scala$reflect$internal$tpe$TypeComparers$$isSameType1(TypeComparers.scala:129)
  scala.reflect.internal.tpe.TypeComparers$class.isSameType(TypeComparers.scala:102)
  scala.reflect.internal.SymbolTable.isSameType(SymbolTable.scala:16)
  scala.reflect.internal.Types$Type.$eq$colon$eq(Types.scala:834)
  scala.reflect.internal.Types$Type.$eq$colon$eq(Types.scala:260)
  ammonite.repl.frontend.DefaultReplAPI$Internal$.print(ReplAPI.scala:293)
`

**Comment by alexarchambault** [comment]
That looks like https://github.com/lihaoyi/Ammonite/issues/535. It should have been fixed recently (in Ammonite).
